name: Update DNS IPs

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'wl/**'
      - 'wl_min/**'

  workflow_dispatch:
          
  schedule:
    - cron: "20 * * * *"


jobs:
  run_script:
    runs-on: ubuntu-24.04

    env:
      # overwrite cache key
      cache-key: dns_lookup_data_cache

    permissions:
      contents: write
      actions: write

    concurrency: 
      group: "single_workflow"  # This is the concurrency key - ensure this workflow only runs one at a time

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Load dns cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: data
        key: ${{ env.cache-key }}

          #    - name: check cache
          #      run: |
          #        mkdir -p data
          #        touch data/dummy
          #        cat data/*
          #        echo data/*

    - name: Commit Files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Apt get
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: iprange curl jq
        cache: yes

    - name: Run DNS queries
      run: |
        bash ./generate.sh

    - name: Delete Previous Cache
      if: ${{ steps.cache-restore.outputs.cache-hit }}
      continue-on-error: true
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "${{ env.cache-key }}" --confirm
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save Cache
      uses: actions/cache/save@v4
      with:
        path: data
        key: ${{ env.cache-key }}

