name: Run Bash Script on Commit

on:
  push:
    branches:
      - main # Specify the branch you want to monitor

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Apt get
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: iprange
        cache: yes

    - name: Run your script
      run: bash ./generate.sh

    - name: Print
      run: |
        ls 
        ls data
        cat data/yts.mx.txt


