name: Run Bash Script on Commit

on:
  push:
    branches:
      - main # Specify the branch you want to monitor

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: iprange
          cache: no

    - name: Run your script
      run: bash ./your_script.sh
