name: Update DNS IPs

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'wl/**'
      - 'wl_min/**'

  workflow_dispatch:
          
  schedule:
    - cron: "30 */6 * * *"


jobs:
  run_script:
    runs-on: ubuntu-24.04

    env:
      # overwrite cache key
      cache-key: your-cache-key

    permissions:
      contents: [read, write]
      actions: write

    concurrency: 
      group: "single_workflow"  # This is the concurrency key - ensure this workflow only runs one at a time

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Load dns cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        key: ${{ env.cache-key }}
        path: data

    - name: check cache
      run: |
        mkdir -p data
        touch data/dummy
        cat data/*
        echo data/*

    - name: Commit Files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Apt get
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: iprange
        cache: yes

    - name: Run your script
      run: |
        bash ./generate.sh
        sleep 20

    - name: Delete Previous Cache
      if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ env.cache-key }}" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Cache
        uses: actions/cache/save@v3
        with:
          path: ./cache
          key: ${{ env.cache-key }}

